name: adyen_drop_in_plugin
description: Flutter plugin to integrate Adyen DropIn UI for Android and iOS.
version: 0.0.2+26
homepage: https://github.com/corgivn/adyen_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

flutter:
  plugin:
    platforms:
      android:
        package: app.adyen.flutter_adyen
        pluginClass: FlutterAdyenPlugin
      ios:
        pluginClass: FlutterAdyenPlugin

